Adds node selector to Kubernetes driver
cnabio/cnab-go pull request #245
Opened 2021-03-25 20:51 UTC by simongdavies

This change introduces a setting to specify node selectors for the Kubernetes driver.

The driver uses a PVC to copy input and output data between the driver and the job that runs the invocation image, In some cases there is a need to make sure that the job runs on a specific node. For example, where the PVC is bound to the node running the driver with ReadWriteOnce access mode then the job running the invocation image must run on the same node, this change enables a client to set the node selector appropriately.

To specify a node selector the client should set the environment variable `NODE_SELECTORS`  with name value pairs separated by whitespace. (e.g 'A=B X=Y').

Signed-off-by: Simon Davies <simongdavies@users.noreply.github.com>

2021-03-29 16:08 UTC, carolynvs commented
For the pod affinity label, is the plan that the k8s operator will generate a unique value, set that on the porter job container, and then pass through this label so that the k8s driver will also use the same label on the invocation image pod?

2021-03-29 16:16 UTC, carolynvs requested changes
This looks great!

2021-03-29 16:16 UTC, carolynvs commented on driver/kubernetes/kubernetes.go
> +			if len(parts) == 2 {
We should have error handling around a poorly formatted pod affinity setting.

2021-03-29 20:04 UTC, simongdavies commented
> For the pod affinity label, is the plan that the k8s operator will generate a unique value, set that on the porter job container, and then pass through this label so that the k8s driver will also use the same label on the invocation image pod?

@carolynvs The approach I have used in the controller is to set the `AFFINITY_MATCH_LABELS` to `installation=inst.Name`. I think this should work?

2021-03-30 15:18 UTC, carolynvs commented
We can chat about that once we have a PR against the operator with this change, but people can run actions against an installation at the same time, though I'd advise anyone against it right now. Ideally it is more unique than the installation name. In another place where I needed a unique value, I used the CRD revision that triggered the event appended to the installation name.

2021-03-30 15:19 UTC, carolynvs approved these changes
LGTM

2021-03-31 20:56 UTC, vdice approved these changes

2021-03-31 22:05 UTC, merged